# Zerodha Paper Trading – template
brokers:
  zerodha:
    broker_name: zerodha
    api_key: "hslyadhjsmm0rtqe"
    api_secret: "sn29e7mctbe42vmgp9quut7mut3ytc30"
    access_token: "UXntoe2mkjr4I7wDekXVSu8giKGHjMSj"  # Generated via login flow on 4 July
    paper_trading: true        # keeps orders virtual (no live execution)

data_feed:
  bar_type: 1MIN
  source: live               # use Zerodha WebSocket stream
  update_frequency: 1        # seconds between tick batches
  # MCX Crude Oil sessions: 09:00–17:00 and 17:00–23:30/23:55.  For simplicity
  # use a single wide window that covers both.
  market_start_time: "09:00"
  market_end_time:   "23:55"

reporting:
  out_dir: runlogs/papertrading/
  html: true
  csv: true

risk_management:
  global_max_daily_loss: 100000.0    # INR
  max_drawdown_limit: 0.15           # 15% intraday drawdown
  global_max_positions: 20

strategies:
  SmaFractalScalper:
    enabled: true
    broker: zerodha
    instrument_id: CRUDEOIL20250721.FUT.MCX   # updated to match available data
    config_file: src/strategies/sma_fractal_scalper/strategy.yaml

logging:
  level: INFO
  file: runlogs/papertrading/paper_trading.log 